### PR TITLE
Use hash in filename as the asset version number

### PR DESCRIPTION
**Pull request by goldenapples**
Previously, asset-loader was returning `null` as the asset version number for assets which contained hashes in their filename. This was done under the assumption that filename-based cache busting meant that there was no need to implement any other type of cache-busting.

However, there are still cricumstances where registering a script with a version number is desirable. One example is when using an nginx http concatenation setup similar to WordPress VIP - if the version number doesn't increment, the static concatenated file will be missing some of it's components.

### CODE REVIEW

**Review by kadamwhite — APPROVED** [review]
Thanks for this, @goldenapples.

We should add this to the [changelog](https://github.com/humanmade/asset-loader/blob/main/CHANGELOG.md) — do you think this necessitates a point or merely a patch release?

**Comment by kadamwhite** [comment]
My inclination is to treat this as a bugfix that we resolve in a patch release, so this would go into 0.6.1. That way it would flow through to Altis projects without requiring the subdependencies within Altis/CMS to be bumped to 0.7.0. I cannot imagine a situation where providing a version number string that stays in sync with the filename could cause a breaking issue.

**Comment by goldenapples** [comment]
I think a patch release should be OK. Even though this does change current functionality, I can't think of a case that you would be expecting no versioning on an asset and having that version string would break something.

**Comment by kadamwhite** [comment]
Sorry @goldenapples, this'll be 0.6.2, @joehoyle didnt add a changelog for https://github.com/humanmade/asset-loader/releases/tag/v0.6.1

**Review by kadamwhite — APPROVED** [review]

**Pull request merged**
